version: '3'
services:
  nginx:
    hostname: nginx
    build:
      context: ./lib/centos7/nginx
      dockerfile: dockerfile
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - /data/nginxhtml/:/usr/local/nginx/html

networks:
  lnmp:
    driver: bridge
