version: '3'
services:
  nginx:
    hostname: nginx
    container_name: nginx-test
    build:
      context: ./lib/centos7/nginx
      dockerfile: dockerfile
    ports:
      - 80:80
    restart: on-failure
    networks:
      - lnmp
    volumes:
      - /data/nginxhtml/:/usr/local/nginx/html
  php:
    hostname: php
    restart: on-failure
    build:
      context: ./lib/centos7/nginx
      dockerfile: dockerfile
    networks:
      - lnmp
    volumes:
      - /wwwroot:/usr/local/nginx/html
  mysql:
    hostname: mysql
    image: mysql:5.6
    ports:
      - 3306:3306
    networks:
      - lnmp
    volumes:
      #- ./mysql/conf:/etc/mysql/conf.d
      - /data/mysql/data:/var/lib/mysql
    command: --character-set-server=utf8
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: usr
      MYSQL_PASSWORD: user123

networks:
  lnmp:
    driver: bridge
