version: '3'
services:
  nginx:
    hostname: nginx
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - 80:80
    volumes:
      - /data/nginxhtml/:/usr/local/nginx/html
